In [1]:
import numpy as np

In [2]:
m1 = np.array([[5,12,8], [1,8,3]])
m1

array([[ 5, 12,  8],
       [ 1,  8,  3]])

In [3]:
m2 = np.array([[5,1,7],[2,4,-5]])
m2

array([[ 5,  1,  7],
       [ 2,  4, -5]])

In [4]:
tensor = np.array([m1,m2])

In [5]:
tensor

array([[[ 5, 12,  8],
        [ 1,  8,  3]],

       [[ 5,  1,  7],
        [ 2,  4, -5]]])

In [6]:
#3D X, Y, Z
tensor.shape

(2, 2, 3)

In [7]:
#Manual
tensor_manual = np.array([[[5,12,3],[3,4,2]],[[3,5,2],[2,5,3]]])
tensor_manual

array([[[ 5, 12,  3],
        [ 3,  4,  2]],

       [[ 3,  5,  2],
        [ 2,  5,  3]]])

In [8]:
m1-m2

array([[ 0, 11,  1],
       [-1,  4,  8]])

In [9]:
m1+m2

array([[10, 13, 15],
       [ 3, 12, -2]])

In [10]:
m1 + 10

array([[15, 22, 18],
       [11, 18, 13]])

In [11]:
m1 + np.array([10])

array([[15, 22, 18],
       [11, 18, 13]])

In [12]:
m1.T

array([[ 5,  1],
       [12,  8],
       [ 8,  3]])

In [13]:
vector = np.array([2,3,4])
vector

array([2, 3, 4])

In [14]:
vector.T

array([2, 3, 4])

In [15]:
vector.shape

(3,)

In [16]:
vetor_new = vector.reshape(1,3)

In [17]:
vetor_new.T

array([[2],
       [3],
       [4]])

In [18]:
np.dot(vector,vector)

29

In [19]:
m1*5

array([[25, 60, 40],
       [ 5, 40, 15]])

In [20]:
m3 = np.array([[5,1,7],[2,4,-5],[5,3,6]])
m3

array([[ 5,  1,  7],
       [ 2,  4, -5],
       [ 5,  3,  6]])

In [21]:
np.dot(m1,m3)

array([[ 89,  77,  23],
       [ 36,  42, -15]])